/home/vaclav/CGAlpha_0.0.1-Aipha_0.0.3/logs/watchdog-systemd.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    su vaclav vaclav
    create 644 vaclav vaclav
}
